name: Workflow Demo
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Create a text file
      run: echo "Hello, world!" >> ./artifacts/hello.txt

    - name: Upload text file
      uses: actions/upload-artifact@v6
      with:
        name: hello-artifact
        path: ./artifacts/hello.txt

  download:
    runs-on: ubuntu-latest
    steps:
    - name: Download text file
      uses: actions/download-artifact@v8
      with:
        name: hello-artifact
        path: ./artifacts

    - name: Read file content
      run: cat ./artifacts/hello.txt
